# Generated by Django 4.2.7 on 2023-12-02 10:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200)),
                ('sluge', models.SlugField()),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='exam.type')),
            ],
        ),
        migrations.DeleteModel(
            name='Subject',
        ),
    ]
