# Generated by Django 4.2.7 on 2024-03-18 06:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0011_alter_user_type'),
        ('exam', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamDone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='child_exam_done', to='accounts.childuser')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_exam_done', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RenameField(
            model_name='exam',
            old_name='subject',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='sluge',
        ),
        migrations.RemoveField(
            model_name='question',
            name='user_answer',
        ),
        migrations.AddField(
            model_name='answerquestion',
            name='exam',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='exam.exam'),
        ),
        migrations.AddField(
            model_name='evaluation',
            name='child',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='child_exam_values', to='accounts.childuser'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='evaluation',
            name='talent',
            field=models.SmallIntegerField(choices=[(1, 'Verbal talent'), (2, 'math talent'), (3, 'space talent'), (4, 'Science talent'), (5, 'music talent'), (6, 'Sports talent'), (7, 'Social aptitude')], default=1),
        ),
        migrations.AddField(
            model_name='exam',
            name='is_last',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='question',
            name='type',
            field=models.SmallIntegerField(choices=[(1, 'Verbal talent'), (2, 'math talent'), (3, 'space talent'), (4, 'Science talent'), (5, 'music talent'), (6, 'Sports talent'), (7, 'Social aptitude')], default=1),
        ),
        migrations.AlterField(
            model_name='evaluation',
            name='grade',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='exam',
            name='type',
            field=models.SmallIntegerField(choices=[(1, '4-7'), (2, '8-11'), (3, '12-15'), (4, 'PARENT')]),
        ),
        migrations.AlterField(
            model_name='question',
            name='exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='exam.exam'),
        ),
        migrations.DeleteModel(
            name='Type',
        ),
    ]
