# Generated by Django 4.2.7 on 2023-12-17 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exam',
            old_name='sluge',
            new_name='slug',
        ),
        migrations.AlterField(
            model_name='exam',
            name='type',
            field=models.SmallIntegerField(choices=[(1, '4-7'), (2, '8-11'), (3, '12-15')]),
        ),
        migrations.DeleteModel(
            name='Type',
        ),
    ]
