# Generated by Django 4.2.7 on 2023-12-17 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0002_rename_sluge_exam_slug_alter_exam_type_delete_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='user_answer',
        ),
    ]
