# Generated by Django 4.2.7 on 2024-03-18 07:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0002_examdone_rename_subject_exam_name_remove_exam_sluge_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='examdone',
            name='exam',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='exam.exam'),
            preserve_default=False,
        ),
    ]
