# Generated by Django 4.2.7 on 2023-12-17 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0003_remove_question_user_answer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='slug',
        ),
    ]
