# Generated by Django 4.2.7 on 2023-12-02 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0003_question_evaluation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='answer',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='type',
            name='choices',
            field=models.CharField(max_length=200),
        ),
    ]
