# Generated by Django 4.2.7 on 2024-03-27 06:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_childuser_which_child'),
        ('exam', '0003_examdone_exam'),
    ]

    operations = [
        migrations.AddField(
            model_name='answerquestion',
            name='child',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='child_answers', to='accounts.childuser'),
        ),
    ]
