# Generated by Django 4.2.7 on 2023-12-02 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0005_remove_question_answer_answerquestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='user_answer',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
