# Generated by Django 4.2.7 on 2024-01-04 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0006_evaluation_talent_question_is_complete_question_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='type',
            field=models.SmallIntegerField(choices=[(1, 'Verbal talent'), (2, 'math talent'), (3, 'space talent'), (4, 'Science talent'), (5, 'music talent'), (6, 'Sports talent'), (7, 'Social aptitude')], default=1),
        ),
    ]
