# Generated by Django 4.2.7 on 2024-01-05 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0008_question_read_only'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='read_only',
        ),
    ]
