# Generated by Django 4.2.7 on 2024-01-05 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0009_remove_question_read_only'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='read_only',
            field=models.BooleanField(default=True),
        ),
    ]
