# Generated by Django 4.2.7 on 2024-01-05 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0010_exam_read_only'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='read_only',
        ),
    ]
