# Generated by Django 4.2.7 on 2024-01-06 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0011_remove_exam_read_only'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exam',
            old_name='subject',
            new_name='name',
        ),
    ]
