# Generated by Django 4.2.7 on 2024-01-30 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0013_alter_evaluation_grade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='is_complete',
        ),
    ]
