# Generated by Django 4.2.7 on 2024-01-30 06:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0014_remove_question_is_complete'),
    ]

    operations = [
        migrations.AddField(
            model_name='answerquestion',
            name='exam',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='exam.exam'),
        ),
    ]
