# Generated by Django 4.2.7 on 2024-01-31 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0015_answerquestion_exam'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='is_last',
            field=models.BooleanField(default=False),
        ),
    ]
