# Generated by Django 4.2.7 on 2024-02-05 08:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0016_exam_is_last'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answerquestion',
            name='question',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='exam.question'),
        ),
    ]
