# Generated by Django 4.2.7 on 2024-03-16 06:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0017_alter_answerquestion_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answerquestion',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.question'),
        ),
    ]
