# Generated by Django 4.2.7 on 2023-12-21 09:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_childuser_birth_date'),
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='moduleschedule',
            name='child',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_user_course', to='accounts.childuser'),
        ),
    ]
