# Generated by Django 4.2.7 on 2024-01-04 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_videocontents'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='videocontents',
            options={'verbose_name': 'video content', 'verbose_name_plural': 'video contents'},
        ),
    ]
