# Generated by Django 4.2.7 on 2024-01-04 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_alter_videocontents_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercourse',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
