# Generated by Django 4.2.7 on 2024-01-10 05:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_userwatchcontent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userwatchcontent',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='userwatchcontent',
            name='object_id',
        ),
        migrations.AddField(
            model_name='userwatchcontent',
            name='content',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='content_user_watch_contents', to='courses.content'),
        ),
    ]
