# Generated by Django 4.2.7 on 2024-01-10 06:50

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0010_remove_userwatchcontent_content_type_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserWatchContent',
            new_name='UserDoneContent',
        ),
    ]
