# Generated by Django 4.2.7 on 2024-01-27 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_rename_userwatchcontent_userdonecontent'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercourse',
            name='is_graduated',
            field=models.BooleanField(default=False),
        ),
    ]
