# Generated by Django 4.2.7 on 2024-01-27 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0012_usercourse_is_graduated'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdonecontent',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.course'),
        ),
    ]
