# Generated by Django 4.2.7 on 2024-03-09 19:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('courses', '0013_userdonecontent_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentPrerequisite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('prerequisite_object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='main_content_type', to='contenttypes.contenttype')),
                ('prerequisite_content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prerequisite_content_type', to='contenttypes.contenttype')),
            ],
        ),
    ]
