# Generated by Django 4.2.7 on 2024-03-09 19:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0014_contentprerequisite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='is_done',
        ),
        migrations.RemoveField(
            model_name='contentprerequisite',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='contentprerequisite',
            name='object_id',
        ),
        migrations.RemoveField(
            model_name='contentprerequisite',
            name='prerequisite_content_type',
        ),
        migrations.RemoveField(
            model_name='contentprerequisite',
            name='prerequisite_object_id',
        ),
        migrations.AddField(
            model_name='contentprerequisite',
            name='content',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='main_content', to='courses.content'),
        ),
        migrations.AddField(
            model_name='contentprerequisite',
            name='prerequisite_content',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='prerequisite_content', to='courses.content'),
        ),
    ]
