# Generated by Django 4.2.7 on 2024-03-09 19:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0015_remove_content_is_done_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentprerequisite',
            name='course',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='prerequisite_course', to='courses.course'),
        ),
    ]
