# Generated by Django 4.2.7 on 2024-03-09 19:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0016_contentprerequisite_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentprerequisite',
            name='content',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='main_content', to='courses.content'),
        ),
        migrations.AlterField(
            model_name='contentprerequisite',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prerequisite_course', to='courses.course'),
        ),
        migrations.AlterField(
            model_name='contentprerequisite',
            name='prerequisite_content',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prerequisite_content', to='courses.content'),
        ),
    ]
