# Generated by Django 4.2.7 on 2024-03-13 07:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_user_type'),
        ('courses', '0017_alter_contentprerequisite_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdonecontent',
            name='child',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_user_done_content_rel', to='accounts.childuser'),
        ),
    ]
