services:
  app:
    build: .
    command: /bin/sh -c " cd src/ && python manage.py migrate && gunicorn config.wsgi -b 0.0.0.0:8000"
    restart: always
    volumes:
      - .:/src
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - rabbitmq
  worker:
    build: .
    command: sh -c "cd src/ && celery -A config worker --loglevel=info"
    volumes:
      - .:/src
    depends_on:
      - rabbitmq
  beat:
    build: .
    command: sh -c  "cd src/ && celery -A config beat -l INFO --scheduler django_celery_beat.schedulers:DatabaseScheduler"
    volumes:
      - .:/src
  postgres:
    image: public.ecr.aws/docker/library/postgres
    environment:
      - "POSTGRES_USER=dbuser"
      - "POSTGRES_PASSWORD=1q2w3e4r5t"
      - "POSTGRES_DB=sanjab"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  rabbitmq:
      image: public.ecr.aws/docker/library/rabbitmq:3.11.26-management
      ports:
        - "5672:5672"
        - "15672:15672"
      environment:
        - "RABBITMQ_DEFAULT_USER=guest"
        - "RABBITMQ_DEFAULT_PASS=guest"