# Generated by Django 4.2.7 on 2024-02-15 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SimpleStattic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('views', models.BigIntegerField()),
                ('type', models.PositiveSmallIntegerField(choices=[(1, 'ALL VIEWS'), (2, 'USERS'), (3, 'REGISTERED COURSE')])),
            ],
        ),
    ]
