# Generated by Django 4.2.7 on 2023-12-03 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('type', models.CharField(choices=[(1, 'FATHER'), (2, 'MOTHER')], max_length=20)),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('father_name', models.CharField(max_length=200)),
                ('national_code', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('birth_date', models.DateField()),
                ('education', models.CharField(max_length=200)),
                ('field_study', models.CharField(max_length=200)),
                ('telephone', models.CharField(max_length=11)),
                ('phone_number', models.CharField(max_length=11, unique=True)),
                ('address', models.CharField(max_length=300)),
                ('Regional_Municipality', models.SmallIntegerField()),
                ('job', models.CharField(blank=True, max_length=200, null=True)),
                ('office_address', models.CharField(blank=True, max_length=200, null=True)),
                ('boys', models.SmallIntegerField()),
                ('girls', models.SmallIntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
