# Generated by Django 4.2.7 on 2024-01-04 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='type',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'FATHER'), (2, 'SANJAB-ADMIN')], null=True),
        ),
    ]
