# Generated by Django 4.2.7 on 2023-12-03 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_is_active_user_phone_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='type',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'FATHER'), (2, 'MOTHER')], null=True),
        ),
    ]
