# Generated by Django 4.2.7 on 2023-12-18 12:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_otpcode_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='childuser',
            name='father',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='father_child', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='childuser',
            name='mother',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mother_child', to=settings.AUTH_USER_MODEL),
        ),
    ]
