# Generated by Django 4.2.7 on 2023-12-21 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_childuser_father_alter_childuser_mother'),
    ]

    operations = [
        migrations.AlterField(
            model_name='childuser',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
