# Generated by Django 4.2.7 on 2023-12-04 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_is_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='childuser',
            name='id',
        ),
        migrations.AlterField(
            model_name='childuser',
            name='national_code',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
