# Generated by Django 4.2.7 on 2023-12-04 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_otpcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='otpcode',
            name='expire_at',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
