# Generated by Django 4.2.7 on 2024-01-30 06:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_userprofile_husband'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='type',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'FATHER'), (2, 'MOTHER'), (3, 'EMPLOYER')], null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='husband',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_profile_husband', to=settings.AUTH_USER_MODEL),
        ),
    ]
