# Generated by Django 4.2.7 on 2024-02-14 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_user_is_super_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='type',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'FATHER'), (2, 'MOTHER'), (3, 'EMPLOYER'), (4, 'SUPER ADMIN')], null=True),
        ),
    ]
