# Generated by Django 4.2.7 on 2024-03-26 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='childuser',
            name='which_child',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
