# Generated by Django 4.2.7 on 2024-03-29 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_childuser_which_child'),
    ]

    operations = [
        migrations.AlterField(
            model_name='childuser',
            name='national_code',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
